<a href="https://colab.research.google.com/github/kalyannaik17/AD-class/blob/main/day10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [7]:
a=np.random.randint(20,60,15)

In [8]:
a

array([31, 44, 39, 37, 49, 39, 50, 20, 29, 46, 31, 38, 37, 27, 34])

In [9]:
a.ndim

1

In [10]:
a[12]

37

In [16]:
a[-2:-10:-1]

array([34, 27, 37, 38, 31, 46, 29, 20, 50])

In [17]:
np.random.seed(94)
b=np.random.randint(45,78,(7,8))
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [22]:
b[2] # 2 row

array([71, 56, 51, 58, 59, 47, 68, 77])

In [23]:
b[:,7] #for 7 col

array([53, 60, 77, 55, 51, 47, 61])

In [25]:
b[3,1] #3 row 1 col

45

In [26]:
b[5,6] #5th row 6th col

67

In [30]:
b[1:5]

array([[61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51]])

In [32]:
b[1:5,1:5]

array([[59, 55, 77, 69],
       [56, 51, 58, 59],
       [45, 52, 74, 65],
       [72, 46, 69, 65]])

In [34]:
#array[row_start : row_end : row_step , col_start : col_end : col_step]

In [35]:
b[3:7,2:7]

array([[52, 74, 65, 53, 60],
       [46, 69, 65, 75, 75],
       [53, 77, 60, 67, 67],
       [74, 69, 54, 64, 52]])

In [36]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [41]:
b[1:7,1:7]

array([[59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60],
       [72, 46, 69, 65, 75, 75],
       [67, 53, 77, 60, 67, 67],
       [54, 74, 69, 54, 64, 52]])

In [39]:
np.random.seed(94)
c=np.random.randint(45,78,(7,8))
c

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [42]:
c[1:7,1:7]

array([[59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60],
       [72, 46, 69, 65, 75, 75],
       [67, 53, 77, 60, 67, 67],
       [54, 74, 69, 54, 64, 52]])

In [43]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [55]:
b[-6:,-7:-1]

array([[59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60],
       [72, 46, 69, 65, 75, 75],
       [67, 53, 77, 60, 67, 67],
       [54, 74, 69, 54, 64, 52]])

In [56]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])

In [57]:
#array[row_start : row_end : row_step , col_start : col_end : col_step]

In [70]:
b[2:7:3,1:8:2]

array([[56, 58, 47, 77],
       [67, 77, 67, 47]])

In [77]:
b[0:7:2,0:8:2]

array([[63, 48, 74, 61],
       [71, 51, 59, 68],
       [64, 46, 65, 75],
       [75, 74, 54, 52]])

In [79]:
b[0:4,1:7]

array([[45, 48, 67, 74, 64, 61],
       [59, 55, 77, 69, 69, 48],
       [56, 51, 58, 59, 47, 68],
       [45, 52, 74, 65, 53, 60]])

In [81]:
b

array([[63, 45, 48, 67, 74, 64, 61, 53],
       [61, 59, 55, 77, 69, 69, 48, 60],
       [71, 56, 51, 58, 59, 47, 68, 77],
       [46, 45, 52, 74, 65, 53, 60, 55],
       [64, 72, 46, 69, 65, 75, 75, 51],
       [75, 67, 53, 77, 60, 67, 67, 47],
       [75, 54, 74, 69, 54, 64, 52, 61]])