<a href="https://colab.research.google.com/github/kalyannaik17/AD-class/blob/main/day9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
stud_2nd=[15,16,17,18,19,20,19,18,19,20,21]

In [12]:
import numpy as np
np.random.randint(15,21,(300))

array([16, 15, 18, 19, 19, 16, 17, 18, 16, 15, 17, 19, 20, 16, 16, 16, 19,
       15, 15, 18, 20, 15, 17, 19, 19, 15, 16, 17, 18, 15, 15, 16, 15, 15,
       18, 17, 16, 19, 17, 18, 18, 15, 15, 20, 18, 18, 18, 20, 19, 16, 16,
       17, 19, 20, 17, 18, 15, 18, 17, 19, 15, 19, 18, 16, 17, 16, 16, 17,
       15, 18, 18, 15, 20, 20, 18, 16, 18, 15, 19, 15, 20, 16, 19, 20, 19,
       20, 19, 20, 19, 15, 17, 18, 17, 20, 19, 19, 17, 18, 18, 15, 18, 18,
       17, 15, 19, 16, 19, 16, 18, 19, 19, 15, 15, 16, 20, 19, 15, 18, 15,
       16, 17, 15, 16, 19, 19, 16, 16, 19, 16, 17, 17, 19, 19, 20, 15, 18,
       15, 19, 15, 15, 20, 19, 18, 15, 17, 16, 16, 15, 17, 15, 19, 17, 20,
       20, 15, 20, 18, 16, 16, 18, 15, 19, 16, 19, 20, 20, 17, 20, 18, 19,
       18, 15, 17, 16, 20, 18, 19, 19, 15, 18, 17, 17, 20, 20, 20, 19, 18,
       19, 17, 15, 19, 20, 19, 20, 15, 15, 16, 17, 17, 19, 18, 16, 17, 15,
       18, 18, 16, 17, 15, 16, 19, 18, 16, 18, 18, 16, 19, 17, 20, 19, 16,
       20, 15, 19, 15, 18

In [15]:
h=np.random.randint(20,99,(6,7))
h

array([[77, 90, 74, 40, 52, 28, 85],
       [84, 21, 60, 88, 47, 63, 69],
       [32, 98, 82, 67, 29, 86, 29],
       [66, 24, 46, 71, 79, 89, 73],
       [66, 64, 76, 23, 26, 80, 28],
       [56, 37, 52, 45, 60, 59, 32]])

In [16]:
import numpy as np

In [20]:
h=np.random.randint(20,99,(6,7))
h

array([[68, 70, 95, 75, 71, 65, 58],
       [93, 66, 46, 35, 67, 28, 36],
       [55, 75, 75, 29, 61, 33, 43],
       [32, 49, 70, 75, 86, 90, 90],
       [37, 65, 23, 64, 77, 87, 45],
       [72, 27, 72, 76, 79, 41, 49]])

In [22]:
#np.random.seed(234)
np.random.randint(20,99,(6,7))

array([[20, 30, 93, 51, 36, 78, 28],
       [22, 45, 91, 47, 24, 36, 44],
       [30, 96, 71, 80, 42, 94, 28],
       [67, 78, 57, 35, 85, 93, 98],
       [84, 84, 93, 36, 93, 94, 96],
       [49, 62, 32, 31, 21, 62, 25]])

In [23]:
m=[5,20,10,6,8]
m

[5, 20, 10, 6, 8]

In [37]:
h=[x**2 for x in m]
h

[25, 400, 100, 36, 64]

In [38]:
g=[m**2 for m in m]
g

[25, 400, 100, 36, 64]

In [39]:
for i in range(len(m)):
    m[i]=m[i]**2
m

[25, 400, 100, 36, 64]

In [45]:
b=(5,20,10,6,8)
b

(5, 20, 10, 6, 8)

In [49]:
b = tuple(x + 5 for x in b)
b

(15, 30, 20, 16, 18)

In [50]:
k=[50,25,85,75,35,45,95]
k


[50, 25, 85, 75, 35, 45, 95]

In [55]:
c = [x for x in k if x < 50]
c

[25, 35, 45]

In [56]:
d=[]
for i in k:
    if i < 50:
        d.append(i)
d

[25, 35, 45]

In [59]:
np.random.seed(5)
arr=np.random.randint(20,90,10)

In [60]:
arr

array([81, 36, 28, 82, 47, 50, 27, 35, 73, 47])

In [61]:
arr+5

array([86, 41, 33, 87, 52, 55, 32, 40, 78, 52])

In [62]:
arr**2

array([6561, 1296,  784, 6724, 2209, 2500,  729, 1225, 5329, 2209])